module.exports={
  "SUCCESS_GLOBAL":{
    "code":"10000",
    "success":true,
    "msg":"成功",
  },
  "SUCCESS_SAVE":{
    "code":"10001",
    "success":true,
    "msg":"保存成功",
  },
  "SUCCESS_DELETE":{
    "code":"10002",
    "success":true,
    "msg":"删除成功",
  },
  "SUCCESS_LOGIN":{
    "code":"10003",
    "success":true,
    "msg":"登录成功",
  },
  "SAVE_EXCEPT_BACKUP":{
    "code":"10004",
    "success":true,
    "msg":"保存成功，备份失败",
  },
  "ERROR_GLOBAL":{
    "code":"20000",
    "success":false,
    "msg":"请求失败",
  },
  "ERROR_UNLOGIN":{
    "code":"20001",
    "success":false,
    "msg":"未登录",
  },
  "ERROR_UNIQUE":{
    "code":"20002",
    "success":false,
    "msg":"该对象已存在",
  },
  "ERROR_NULL":{
    "code":"20003",
    "success":false,
    "msg":"参数为空",
  },
  "ERROR_MISS":{
    "code":"20004",
    "success":false,
    "msg":"参数缺失",
  },
  "ERROR_LOGIN":{
    "code":"20005",
    "success":false,
    "msg":"登录失败",
  }
};