module.exports =  [
    {
        version:'v1.0.0',
        duration:'2020/04/01-',
        logs:[
            {
                day:'Day3',
                daily:[
                    "async/await改写异步",
                    "try-catch异常捕获",
                    "express-winston 日志中间件",
                    "书签导入",
                    "书签分组"
                ]
            },
            {
                day:'Day2',
                daily:[
                    "PicGo本地图床",
                    "bookmark | list/save/delete",
                    "swagger-yaml",
                    "code-errorCode定义"
                ]
            },
            {
                day:'Day1',
                daily:[
                    "express环境",
                    "express-swagger-ui",
                    "express 启动字符画"
                ]
            }
        ]
    },
    {
        version:'v0.0.1',
        duration:'2020/3/17-2020/03/31',
        logs:[
            {
                day:'Day9',
                daily:[
                    "home页开发",
                    "布局调整",
                    "路由调整",
                    "文档编撰"
                ]
            },
            {
                day:'Day8',
                daily:[
                    "element-Ui引入",
                    "blog页-类目树",
                    "blog页-文章流"
                ]
            },
            {
                day:'Day7',
                daily:[
                    "整理需求按优先级排序",
                    "blog页基础布局",
                    "config配置文件定义"
                ]
            },
            {
                day:'Day6',
                daily:[
                    "创建doc_工程存放博客并定义 md快捷方式",
                    "header开发",
                    "link页开发"
                ]
            },
            {
                day:'Day5',
                daily:[
                    "footer开发",
                    "modal设计开发",
                    "home设计",
                    "blog设计",

                ]
            },
            {
                day:'Day4',
                daily:[
                    "地理坐标获取",
                    "日出日落功能实现",
                    "tower层优化与夜间效果",
                    "footer内容设计"
                ]
            },
            {
                day:'Day3',
                daily:[
                    "txt，艺术字，配色调整",
                    "cloud动画",
                    "tower抠图",
                    "star-sky滚动条问题",
                    "调研根据坐标＆时间计算日出日落"
                ]
            },
            {
                day:'Day2',
                daily:[
                    "vuex-store回顾与实装",
                    "start页分层dom设计",
                    "start txt层悬浮交互"
                ]
            },
            {
                day:'Day1',
                daily:[
                    "设计初稿",
                    "vue-cli构建工程",
                    "开发路由设计"
                ]
            }
        ]
    }
];